export const menu = [
    {
        name:"home",
        title:'首页',
        url:""
    },{
        name:"developer",
        title:'第二开发商',
        url:"/developer"
    },{
        name:"product",
        title:'精装产品',
        url:"/product"
    },{
        name:"design",
        title:'“慧”设计',
        url:"/design"
    },{
        name:"case",
        title:'案例',
        url:"/case"
    },{
        name:"cooperate",
        title:'合作伙伴',
        url:"/cooperate"
    }
]